exports.VUE_APOLLO_QUERY_KEYWORDS = [
  'variables',
  'watch',
  'update',
  'result',
  'error',
  'loadingKey',
  'watchLoading',
  'skip',
  'throttle',
  'debounce',
  'initDebounce',
  'subscribeToMore',
  'prefetch',
  'manual',
]
